# Generated by Django 3.2.23 on 2023-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hrfhgrri', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
